export const GET_PRODUCTS = "GET_PRODUCTS";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const HOME_INFO = "HOME_INFO";
export const DISCOUNT_PRODUCTS = "DISCOUNT_PRODUCTS";
